trigger:
- master

pool:
  name: Default

steps:
- script: echo My first Azure Pipeline for Maven project
  displayName: 'Run a one-line script'

- script: mvn clean install
  displayName: 'Build with Maven'

- script: mvn exec:java -Dexec.mainClass="com.example.App"
  displayName: 'Run JAR file'